apiVersion: v2
name: wasp-routing-service
appVersion: '2.0.4'
description: A Helm chart for WASP-ROUTING_SERVICE
version: '2.0.4'
type: application
maintainers:
  - name: digicatapult
    email: opensource@digicatapult.org.uk
    url: www.digicatapult.org.uk

dependencies:
  - name: kafka
    version: '12.7.3'
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
