apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wasp-routing-service.fullname" . }}-config
  labels:
    {{- include "wasp-routing-service.labels" . | nindent 4 }}
data:
  waspRoutingServicePort: {{ .Values.config.waspRoutingServicePort | quote }}
  logLevel: {{ .Values.config.logLevel | quote }}
  kafkaLogLevel: {{ .Values.config.kafkaLogLevel | quote }}
  kafkaBrokers: {{ include "wasp-routing-service.kafka.brokers" . }}
  thingsHost: {{ .Values.config.waspThingsHost }}
  thingsPort: {{ .Values.config.waspThingsPort | quote }}
  rawPayloadsPartitions: {{ .Values.config.rawPayloadsPartitions | quote }}
  rawPayloadsReplicationFactor: {{ .Values.config.rawPayloadsReplicationFactor | quote }}
