apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wasp-routing-service.fullname" . }}
  labels:
    {{- include "wasp-routing-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ include "wasp-routing-service.fullname" . }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        name: {{ include "wasp-routing-service.fullname" . }}
    spec:
      {{- include "wasp-routing-service.imagePullSecrets" . | indent 6 }}
      initContainers:
        - name: {{ include "wasp-routing-service.initRawpayloads.name" . }}
          image: bitnami/kafka:2.7.0-debian-10-r68
          envFrom:
            - configMapRef:
                name: {{ include "wasp-routing-service.fullname" . }}-config
          command: ['/bin/sh', '-c']
          args: ['/opt/bitnami/kafka/bin/kafka-topics.sh --create --topic raw-payloads --bootstrap-server=$(kafkaBrokers) --partitions $(rawPayloadsPartitions) --replication-factor $(rawPayloadsReplicationFactor) --if-not-exists']
      containers:
        - name: {{ include "wasp-routing-service.fullname" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.config.waspRoutingServicePort }}
            initialDelaySeconds: 45
            timeoutSeconds: 3
            periodSeconds: 5
          env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-routing-service.fullname" . }}-config
                  key: logLevel
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-routing-service.fullname" . }}-config
                  key: waspRoutingServicePort
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name:  {{ include "wasp-routing-service.fullname" . }}-config
                  key: kafkaBrokers
            - name: KAFKA_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name:  {{ include "wasp-routing-service.fullname" . }}-config
                  key: kafkaLogLevel
            - name: THINGS_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-routing-service.fullname" . }}-config
                  key: thingsHost
            - name: THINGS_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-routing-service.fullname" . }}-config
                  key: thingsPort
